import type { NextPage } from 'next';
import Head from 'next/head';
import Searchbar from '../components/Searchbar';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Plantery</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Plantery</h1>
        <Searchbar />
      </main>
    </div>
  );
};

export default Home;
